import type { CapabilityMatrix } from './contracts/sandboxCapabilities.js';

export const DIRECT_E2B_CAPABILITIES: CapabilityMatrix = {
  commandExecution: true,
  backgroundCommands: true,
  pty: true,
  ptyInput: true,
  ptyResize: true,
  filesystemRead: true,
  filesystemWrite: true,
  filesystemDelete: true,
  exposedPorts: true,
  snapshots: false,
  pause: false,
  resume: true,
  autoResume: false,
  workspacePersistence: true,
  manifestFiles: false,
  manifestGitRepos: false,
  ephemeralEnvironment: true,
  archiveExport: false,
  archiveImport: false,
};

export const OPENAI_AGENTS_E2B_CAPABILITIES: CapabilityMatrix = {
  commandExecution: true,
  backgroundCommands: true,
  pty: true,
  ptyInput: true,
  ptyResize: true,
  filesystemRead: true,
  filesystemWrite: true,
  filesystemDelete: true,
  exposedPorts: true,
  snapshots: false,
  pause: false,
  resume: true,
  autoResume: false,
  workspacePersistence: true,
  manifestFiles: false,
  manifestGitRepos: false,
  ephemeralEnvironment: true,
  archiveExport: false,
  archiveImport: false,
};
